	写一个程序，给出参数x,w,b,能够计算神经网络里面的输出g(z)，其中
 
z=wx+b
自己设置w 矩阵，x向量和b向量。

In [1]:
import math
import numpy as np
def sigmoid(z):
    return 1/(1+math.exp(-z))

In [6]:
class Perceptor(object):
    def __init__(self,w,b):
        self.w=w
        self.b=b
    def __call__(self,x):    
        return sigmoid(np.dot(x,self.w)+self.b)
p=Perceptor([1,2,3],-4)
output=p([1,1,0])
print(output)
output=p([1,0,1])
print(output)

0.2689414213699951
0.5

（1）假设PM_dongsi，PM_dongsihuan, PM_nongzhanguan的污染值分别表示：重度污染>150, 中度污染>75，轻度污染>35，良好>0，那么求不同程度的污染所占用的时间比例。（去掉NA值的行）
（2）求2013年每月各个地区（东四，东四环和农展馆）的PM值的平均值

In [3]:
import numpy as np
import pandas as pd
data = pd.read_csv('C:/Users/Swywy/Desktop/大三上学习/人工神经网络/BeijingPM.csv') 
data=data[['year','month','PM_Dongsi','PM_Dongsihuan','PM_Nongzhanguan']]

In [4]:
def get(place):
    d=[]
    d.append(len(data[(data[place]>150)]))
    d.append(len(data[(data[place]>75)&(data[place]<=150)]))
    d.append(len(data[(data[place]>35)&(data[place]<=75)]))
    d.append(len(data[(data[place]<=35)]))
    return d
dongsi=get('PM_Dongsi')
dongsihuan=get('PM_Dongsihuan')
nongzhanguan=get('PM_Nongzhanguan')
con={'东四':dongsi,"东四环":dongsihuan,"农展馆":nongzhanguan}
df=pd.DataFrame(con)
df['东四']=df['东四']/df['东四'].sum()
df['东四环']=df['东四环']/df['东四环'].sum()
df['农展馆']=df['农展馆']/df['农展馆'].sum()
df['东四']=df['东四'].apply(lambda x: '%.2f%%' % (x*100))
df['东四环']=df['东四环'].apply(lambda x: '%.2f%%' % (x*100))
df['农展馆']=df['农展馆'].apply(lambda x: '%.2f%%' % (x*100))
rename=['重度污染','中度污染','轻度污染','良好']
df.index=rename
df

          东四     东四环     农展馆
重度污染  18.48%  18.79%  18.19%
中度污染  25.62%  27.39%  24.84%
轻度污染  22.74%  23.75%  23.45%
良好    33.16%  30.07%  33.52%

In [5]:
data=data[data['year']==2013]
avgData=[]
for i in range(1,13):
    avgData.append(data[data['month']==i].mean())
df=pd.DataFrame(avgData)
df=df.astype({'year':'int','month':'int'})
df

    year  month   PM_Dongsi  PM_Dongsihuan  PM_Nongzhanguan
0   2013      1  182.928161            NaN       185.770115
1   2013      2  111.057722            NaN       106.996880
2   2013      3  109.900277     128.668810       108.195833
3   2013      4   64.780802      63.973646        56.634286
4   2013      5   91.126741     102.015320        76.914169
5   2013      6  109.303426     117.133545       106.601027
6   2013      7   73.468413      84.608558        74.079529
7   2013      8   64.407625      74.063920        68.245566
8   2013      9   84.791066      81.961765        81.097183
9   2013     10  103.535191     101.410437        96.520685
10  2013     11   82.917827      83.772028        83.344491
11  2013     12   86.883081      92.051355        89.369014